language: c

compiler: gcc

env:
    global:
        - SDK=0.9.5
        - SANITYCHECK_OPTIONS=" --inline-logs -N"
        - SANITYCHECK_OPTIONS_RETRY=" --only-failed --outdir=out-2nd-pass"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.9.5
        - ZEPHYR_TOOLCHAIN_VARIANT=zephyr
        - USE_CCACHE=1
        - COVERAGE="--all "
        - QEMU_BIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/
        - QEMU_BIOS=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/share/qemu
        - DTC=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
        - MATRIX_BUILDS="25"
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"
        - MATRIX_BUILD="7"
        - MATRIX_BUILD="8"
        - MATRIX_BUILD="9"
        - MATRIX_BUILD="10"
        - MATRIX_BUILD="11"
        - MATRIX_BUILD="12"
        - MATRIX_BUILD="13"
        - MATRIX_BUILD="14"
        - MATRIX_BUILD="15"
        - MATRIX_BUILD="16"
        - MATRIX_BUILD="17"
        - MATRIX_BUILD="18"
        - MATRIX_BUILD="19"
        - MATRIX_BUILD="20"
        - MATRIX_BUILD="21"
        - MATRIX_BUILD="22"
        - MATRIX_BUILD="23"
        - MATRIX_BUILD="24"
        - MATRIX_BUILD="25"

build:
    cache: true
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.5-rc4
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - git submodule update --remote
      - cd zephyr
      - source zephyr-env.sh
      - ccache -c -s --max-size=5000M
      - >
          if [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify" -o "$JOB_TRIGGERED_BY_NAME" = "undefined" ]; then
            echo "- Building with --all --enable-slow";
          elif [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify-debug" ]; then
            export CONFIG_DEBUG=y
            echo "- Building with --all --enable-slow";
          elif [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify-arm" ]; then
            echo "- Building with ARM cross toolchain";
            export GCCARMEMB_TOOLCHAIN_PATH=/opt/toolchain/arm-none-eabi
            export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          fi;
      - >
        ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${COVERAGE} ${SANITYCHECK_OPTIONS};
        if [ "$?" != "0" ]; then
          sleep 10;
          ./scripts/sanitycheck ${SANITYCHECK_OPTIONS} ${SANITYCHECK_OPTIONS_RETRY} || true;
        fi;
        if [ "$?" != "0" ]; then
          sleep 10;
          ./scripts/sanitycheck ${SANITYCHECK_OPTIONS} ${SANITYCHECK_OPTIONS_RETRY} || true;
        fi;
      - ccache -s
    on_success:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./scripts/sanity_chk/last_sanity.xml ]; then
          cp ./scripts/sanity_chk/last_sanity.xml ../shippable/testresults/;
        fi;
    on_failure:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./scripts/sanity_chk/last_sanity.xml ]; then
          cp ./scripts/sanity_chk/last_sanity.xml ../shippable/testresults/;
        fi;

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds+int+399+7809482394022958124@lists.zephyrproject.org
      branches:
        only:
          - master
      on_success: never
      on_failure: always
