language: c

compiler: gcc

env:
    global:
        - SANITYCHECK_OPTIONS=" --inline-logs -N --build-only --all --retry-failed 3 -v "
        - MATRIX_BUILDS="30"
        - ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.11.2
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"
        - MATRIX_BUILD="7"
        - MATRIX_BUILD="8"
        - MATRIX_BUILD="9"
        - MATRIX_BUILD="10"
        - MATRIX_BUILD="11"
        - MATRIX_BUILD="12"
        - MATRIX_BUILD="13"
        - MATRIX_BUILD="14"
        - MATRIX_BUILD="15"
        - MATRIX_BUILD="16"
        - MATRIX_BUILD="17"
        - MATRIX_BUILD="18"
        - MATRIX_BUILD="19"
        - MATRIX_BUILD="20"
        - MATRIX_BUILD="21"
        - MATRIX_BUILD="22"
        - MATRIX_BUILD="23"
        - MATRIX_BUILD="24"
        - MATRIX_BUILD="25"
        - MATRIX_BUILD="26"
        - MATRIX_BUILD="27"
        - MATRIX_BUILD="28"
        - MATRIX_BUILD="29"
        - MATRIX_BUILD="30"

build:
    cache: false
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.11.6
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - git submodule update --remote
      - west init -l zephyr
      - west update
      - cd zephyr
      - export QEMU_BIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/
      - export QEMU_BIOS=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/share/qemu
      - export DTC=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
      - source zephyr-env.sh
      - >
        ./scripts/sanitycheck --build-only --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${SANITYCHECK_OPTIONS};
    on_success:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./sanity-out/sanitycheck.xml ]; then
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
        fi;
    on_failure:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./sanity-out/sanitycheck.xml ]; then
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
        fi;

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds+int+399+7809482394022958124@lists.zephyrproject.org
      branches:
        only:
          - master
      on_success: always
      on_failure: always
